// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7BYZsa0zaQXwsz8yuQPdOh1feUOIuba8',
    appId: '1:358919697629:web:de231bf5102eb469625734',
    messagingSenderId: '358919697629',
    projectId: 'serviceapptest-9f6f0',
    authDomain: 'serviceapptest-9f6f0.firebaseapp.com',
    storageBucket: 'serviceapptest-9f6f0.appspot.com',
    measurementId: 'G-3VL2RDZFNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY9xR4XErE0Ferufc15_wTIgpryXcczqA',
    appId: '1:358919697629:android:efede128c44ecc5e625734',
    messagingSenderId: '358919697629',
    projectId: 'serviceapptest-9f6f0',
    storageBucket: 'serviceapptest-9f6f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJd1YG2P_iqN9iQ-vKc7X-jkpsgQbDBcQ',
    appId: '1:358919697629:ios:833f068667f2c172625734',
    messagingSenderId: '358919697629',
    projectId: 'serviceapptest-9f6f0',
    storageBucket: 'serviceapptest-9f6f0.appspot.com',
    iosBundleId: 'com.example.gp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJd1YG2P_iqN9iQ-vKc7X-jkpsgQbDBcQ',
    appId: '1:358919697629:ios:c84ba3298c40a01a625734',
    messagingSenderId: '358919697629',
    projectId: 'serviceapptest-9f6f0',
    storageBucket: 'serviceapptest-9f6f0.appspot.com',
    iosBundleId: 'com.example.gp.RunnerTests',
  );
}
